Add menu and lobby
olekgolus11/BAM pull request #17
Opened 2023-06-02 22:30 UTC by BartoszChadrys

2023-06-03 15:00 UTC, olekgolus11 requested changes
This looks reallyyyy gooood

2023-06-04 09:13 UTC, BartoszChadrys commented on Client.py
> +            for event in pygame.event.get():
You are right, I changed it to enum

2023-06-04 09:13 UTC, BartoszChadrys commented on Menu/Button.py
> +        self.textInput = textInput
Yes, I fix it and make it in two seperate lines

2023-06-04 09:19 UTC, BartoszChadrys commented on Menu/Menu.py
> +        width = 1150
It's hard to depend on window size value, so I just set constants to height and width in constants.py

2023-06-04 09:23 UTC, BartoszChadrys commented on Menu/Menu.py
> +
True, I fix some of these extra lines

2023-06-04 17:47 UTC, olekgolus11 approved these changes

2023-06-04 17:47 UTC, merged